---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  #no_log: "{{ molecule_no_log }}"
  collections:
    - community.kubernetes
  tasks:
    - name: Delete namespace
      k8s:
        api_version: v1
        kind: Namespace
        name: '{{ namespace }}'
        state: absent
        wait: yes
    - name: Delete K8S resources
      k8s:
        definition: "{{ lookup('template', '/'.join([deploy_dir, item])) }}"
        namespace: '{{ namespace }}'
        state: absent
        wait: yes
      with_items:
        - role.yaml
        - role_binding.yaml
        - service_account.yaml
        - notify-subscription-secret.yaml
        - shared-pv.yaml
        - shared-pvc.yaml
    - name: Delete Custom Resource Definition
      k8s:
        definition: |
          {{ lookup('file', '/'.join([deploy_dir, 'crds/dispatcher.pacifica.io_pacificadispatchers_crd.yaml'])) }}
        state: absent
        wait: yes
    - name: Remove an image
      docker_image:
        name: localhost:5000/pacifica/pacifica-dispatcher-operator
        tag: latest
        state: absent
      ignore_errors: true
